
---
- name: Costomase EC2-Client
  hosts: aws
  become: yes

  vars:
    destin_folder           : /var/www/html

  tasks:
  - name: Check and Print Linux version
    debug:
      var: ansible_os_family

  - block: #Install Apache RedHat
    - name: Install Apache Web Server
      yum: name=httpd state=latest
    - name: AutoStart Apache
      service: name=httpd state=started enabled=yes
    when: ansible_os_family == "RedHat"

  - name: Copy INDEX.HTML file
    copy: src=./index.html dest={{ destin_folder }}/index.html mode=555
    notify:
      - Restart Apache RedHat

  handlers:
  - name: Restart Apache RedHat
    service: name=httpd state=restarted 
    when: ansible_os_family == "RedHat"

